= Demo for Ingress Controller sharding in OCP 4



oc edit ingress.config.openshift.io/cluster





oc patch ingresscontroller default -n openshift-ingress-operator --type=merge -p '{"spec":{"domain":"subdomian1.myopenshift-725535-5c19b80d0b42bf06f50309d5c8a080e8-0000.ams03.containers.appdomain.cloud"}}'



The idea is to Split Ingress traffic according to 

** Enable Ingress Controller sharding
** Enable Network polices

Ingress Controller sharding is useful when balancing incoming traffic load among a set of Ingress Controllers and when isolating traffic to a specific Ingress Controller
** To control that specific Pods will only accept communication form DMZ green or purple we will implement NetworkPolicy
* Impact:
** Segregate Ingress traffic through Ingress Controller Sharding; Dedicate 2 infra nodes (1 HA router shard) for each <<14-abbrev adoc#abbr-dmz-color-codes,DMZ color code>>
** Additional Worker Nodes will be placed in each <<14-abbrev.adoc#abbr-dmz-color-codes,DMZ Color Code>> to have the ability of communication with the respective DMZ shard,
and it will host applications' pods which should only accept communication from the ingress shard
** Implement NetworkPolicy to control Ingress to the Pods isolation.


.References :
** https://github.com/bitnami-labs/sealed-secrets["Sealed Secrets" for Kubernetes]

:sectnums:

== Understand Sealed Secrets


[source,bash]
----
ibmcloud oc nlb-dns ls --cluster myclustername
----



https://cloud.ibm.com/docs/openshift?topic=openshift-loadbalancer_hostname#loadbalancer_hostname_format
In the subdomain that you copied, change the i00<n> value in the subdomain to 000<n+1>. For example, the myclustername-870445-5c19b80d0b42bf06f50309d5c8a080e8-0000.ams03.containers.appdomain.cloud subdomain is changed to myclustername-870445-5c19b80d0b42bf06f50309d5c8a080e8-0001.ams03.containers.appdomain.cloud. The 0 value indicates a public subdomain, and the n+1 value indicates the next consecutive subdomain that you create in this cluster. 

https://cloud.ibm.com/docs/openshift?topic=openshift-loadbalancer_hostname#loadbalancer_hostname_dns

oc apply -f sharded-ingress-controller.yaml

oc get svc router-sharded-ingress-controller  -n openshift-ingress



ibmcloud oc nlb-dns create vpc-classic --cluster myclustername --lb-host myclustername-870445-5c19b80d0b42bf06f50309d5c8a080e8-0001.ams03.containers.appdomain.cloud --type public --secret-namespace openshift-ingress

ibmcloud oc nlb-dns create classic --cluster myclustername --type public --secret-namespace openshift-ingress --ip 169.50.129.106




ibmcloud oc nlb-dns monitor ls --cluster <cluster_name_or_id>

ibmcloud oc nlb-dns monitor configure --cluster <cluster_name_or_id> --nlb-host <host_name> --enable --description <description> --type <type> --method <method> --path <path> --timeout <timeout> --retries <retries> --interval <interval> --port <port> --header <header> --expected-body <expected-body> --expected-codes <expected-codes> --follows-redirects <true> --allows-insecure <true>
