= Manage API Objects, using Kustomize

The idea of

.References :
** https://argoproj.github.io/argo-cd/operator-manual/[]
** https://www.openshift.com/blog/openshiftauthentication-integration-with-argocd[]

:sectnums:
== High level architecture

* Deployment Strategy
** Using Operator vs Manifests.
* Deployment scope
** Central/Single “ArgoCD” instance managing many applications
* Deployment types
** Configure HA: This runs more containers, and run Redis in HA mode (The HA installation will require at least three different nodes due to pod anti-affinity roles in the specs).
*  Authentication
** OpenShift integrated ? https://www.openshift.com/blog/openshiftauthentication-integration-with-argocd
▪ Use Argo Auth provider
o Storing sensitive values – Secret Management
Commented [Si'HW(1]: Needs to be verified
▪ https://git-secret.io/ (for time being)
▪ https://www.openshift.com/blog/gitops-secret-management
o RBAC
▪ If users are going to interact with ArgoCD via CLI (or other non-UI tooling) an
additional RBAC role is required to grant them access to create Application
CR
o SSL Certificates for route
o Git Repositories
▪ SSH configuration (if needed)
o Metrics (Prom integration)

== Deployment Strategy

For installing the ArgoCD, we will use the Operator. for more details see

link:argocd-operator[installing ArgoCD Operator]
